# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: macos-10.13
  env: 
    WIN32_CC: /usr/local/Cellar/mingw-w64/6.0.0_1/bin/i686-w64-mingw32-gcc

steps:
- script: brew install mingw-w64
- script: make
- script: make ng.exe
